# Generated by Django 4.1 on 2022-09-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeRegisterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeregister',
            name='info',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timeregister',
            name='key',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
