# Generated by Django 4.1 on 2022-10-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeRegisterApp', '0003_alter_timeregister_entry_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebank',
            name='hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timebank',
            name='negative_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timebank',
            name='positive_hours',
            field=models.IntegerField(),
        ),
    ]
